<?php

namespace Database\Seeders;

use App\Models\Booking;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class BookingSeeder extends Seeder
{
    public function run(): void
    {
        $statuses = ['pending', 'paid', 'rented', 'returned', 'cancelled', 'expired'];

        foreach ($statuses as $status) {
            $booking = Booking::factory()->create([
                'status' => $status,
                'cancel_reason' => $status === 'cancelled' ? 'Berubah rencana (seeder)' : null,
            ]);

            // Create History
            $booking->histories()->create([
                'from_status' => $status === 'pending' ? null : 'pending',
                'to_status' => $status,
                'note' => 'Generated by seeder',
            ]);

            // Create Payment
            $paymentStatus = match ($status) {
                'pending' => 'pending',
                'expired' => 'expired',
                'cancelled' => 'failed',
                default => 'paid',
            };

            $booking->payments()->create([
                'method' => 'xendit_invoice',
                'amount' => $booking->total_amount,
                'status' => $paymentStatus,
                'expires_at' => Carbon::now()->addHours(24),
                'paid_at' => $paymentStatus === 'paid' ? Carbon::now() : null,
            ]);
        }
    }
}
